
#ifndef CONSTANTS
#define CONSTANTS

/*Resource types*/
#define RESOURCE_COUNT 26

/*Agriculture*/
#define CEREALS 0
#define VEGETABLES_AND_FRUIT 1
#define MEAT 2
#define DAIRY 3
#define TOBACCO 4
#define DRUGS 5

/*Energy*/
#define ELECTRICITY 6
#define FOSSIL_FUELS 7

/*Raw materials*/
#define WOOD_AND_PAPER 8
#define MINERALS 9
#define IRON_AND_STEEL 10
#define PRECIOUS_STONES 11

/*Industrial goods*/
#define FABRICS 12
#define PLASTICS 13
#define CHEMICALS 14
#define PHARMACEUTICALS 15

/*Finished goods*/
#define APPLIANCES 16
#define VEHICLES 17
#define MACHINERY 18
#define COMMODITIES 19

/*Services*/
#define CONSTRUCTION 20
#define ENGINEERING 21
#define HEALTHCARE 22
#define RETAIL 23
#define LEGAL_SERVICES 24
#define MARKETING 25

/*Resource dependencies*/
#define UNITS_OUTPUT_PER_INPUT 60

#define CEREALS_MEAT 5
#define CEREALS_DAIRY 5

#define MACHINERY_FOSSIL_FUELS 10

#define MACHINERY_WOOD_AND_PAPER 10
#define ELECTRICITY_WOOD_AND_PAPER 5
#define MACHINERY_MINERALS 10
#define ELECTRICITY_IRON_AND_STEEL 10
#define MACHINERY_PRECIOUS_STONES 5

#define ELECTRICITY_FABRICS 5
#define CHEMICALS_PLASTICS 10
#define ELECTRICITY_PLASTICS 5
#define ELECTRICITY_CHEMICALS 5
#define CHEMICALS_PHARMACEUTICALS 10
#define ELECTRICITY_PHARMACEUTICALS 5

#define IRON_AND_STEEL_APPLIANCES 10
#define ELECTRICITY_APPLIANCES 5
#define IRON_AND_STEEL_VEHICLES 15
#define PLASTICS_VEHICLES 10
#define ELECTRICITY_VEHICLES 5
#define IRON_AND_STEEL_MACHINERY 15
#define ELECTRICITY_MACHINERY 5
#define PLASTICS_COMMODITIES 10
#define CHEMICALS_COMMODITIES 10
#define FABRICS_COMMODITIES 5
#define ELECTRICITY_COMMODITIES 5

#define IRON_AND_STEEL_CONSTRUCTION 15
#define WOOD_AND_PAPER_CONSTRUCTION 10
#define MACHINERY_CONSTRUCTION 5
#define PHARMACEUTICALS_HEALTHCARE 10
#define MARKETING_RETAIL 5

#endif