#include "constants.h"

const int FOOD_TYPES[] = { CEREALS, VEGETABLES_AND_FRUIT, DAIRY, MEAT };
const int BASIC_GOOD_TYPES[] = { TOBACCO, DRUGS, ELECTRICITY, FOSSIL_FUELS, MINERALS, WOOD_AND_PAPER, COMMODITIES, RETAIL };
const int LUXURY_GOOD_TYPES[] = { PRECIOUS_STONES, APPLIANCES, VEHICLES, PHARMACEUTICALS, HEALTHCARE, LEGAL_SERVICES };