
#ifndef CONSTANTS
#define CONSTANTS

/*Resource types*/
#define RESOURCE_COUNT 26

/*Agriculture*/
#define CEREALS 0
#define VEGETABLES_AND_FRUIT 1
#define MEAT 2
#define DAIRY 3
#define TOBACCO 4
#define DRUGS 5

/*Energy*/
#define ELECTRICITY 6
#define FOSSIL_FUELS 7

/*Raw materials*/
#define WOOD_AND_PAPER 8
#define MINERALS 9
#define IRON_AND_STEEL 10
#define PRECIOUS_STONES 11

/*Industrial goods*/
#define FABRICS 12
#define PLASTICS 13
#define CHEMICALS 14
#define PHARMACEUTICALS 15

/*Finished goods*/
#define APPLIANCES 16
#define VEHICLES 17
#define MACHINERY 18
#define COMMODITIES 19

/*Services*/
#define CONSTRUCTION 20
#define ENGINEERING 21
#define HEALTHCARE 22
#define RETAIL 23
#define LEGAL_SERVICES 24
#define MARKETING 25

/*
Resource dependencies
These values are used to calculate resource consumption generated by industry
*/
#define UNITS_OUTPUT_PER_INPUT 60

#define CEREALS_MEAT 5
#define CEREALS_DAIRY 5

#define MACHINERY_FOSSIL_FUELS 10

#define MACHINERY_WOOD_AND_PAPER 10
#define ELECTRICITY_WOOD_AND_PAPER 5
#define MACHINERY_MINERALS 10
#define ELECTRICITY_IRON_AND_STEEL 10
#define MACHINERY_PRECIOUS_STONES 5

#define ELECTRICITY_FABRICS 5
#define CHEMICALS_PLASTICS 10
#define ELECTRICITY_PLASTICS 5
#define ELECTRICITY_CHEMICALS 5
#define CHEMICALS_PHARMACEUTICALS 10
#define ELECTRICITY_PHARMACEUTICALS 5

#define IRON_AND_STEEL_APPLIANCES 10
#define ELECTRICITY_APPLIANCES 5
#define IRON_AND_STEEL_VEHICLES 15
#define PLASTICS_VEHICLES 10
#define ELECTRICITY_VEHICLES 5
#define IRON_AND_STEEL_MACHINERY 15
#define ELECTRICITY_MACHINERY 5
#define PLASTICS_COMMODITIES 10
#define CHEMICALS_COMMODITIES 10
#define FABRICS_COMMODITIES 5
#define ELECTRICITY_COMMODITIES 5

#define IRON_AND_STEEL_CONSTRUCTION 15
#define WOOD_AND_PAPER_CONSTRUCTION 10
#define MACHINERY_CONSTRUCTION 5
#define PHARMACEUTICALS_HEALTHCARE 10
#define MARKETING_RETAIL 5

/*Scaling values*/
#define POPULATION_SCALING 1000
#define GDP_SCALING 1000000

#define MIN_CEREAL_CONSUMPTION 3
/*
The ratio of spending on each class of resource will vary based on the income per capita
Low incomes will have a higher portion of food spending, higher levels of spending will have increasing portions of finished goods followed by services
*/
#define LOW_INCOME_CAP 12
#define MIDDLE_INCOME_CAP 30

#define FOOD_COUNT 4
#define BASIC_GOODS_COUNT 8
#define LUXURY_GOODS_COUNT 6
const int FOOD_TYPES[FOOD_COUNT];
const int BASIC_GOOD_TYPES[BASIC_GOODS_COUNT];
const int LUXURY_GOOD_TYPES[LUXURY_GOODS_COUNT];

#define LOW_INCOME_FOOD 0.95
#define LOW_INCOME_BASIC 0.05
#define LOW_INCOME_LUXURY 0.0
#define MIDDLE_INCOME_FOOD 0.4
#define MIDDLE_INCOME_BASIC 0.4
#define MIDDLE_INCOME_LUXURY 0.2
#define HIGH_INCOME_FOOD 0.1
#define HIGH_INCOME_BASIC 0.3
#define HIGH_INCOME_LUXURY 0.6
typedef struct ClassSpendingProfile
{
    float food;
    float basicGoods;
    float luxuryGoods;
} ClassSpendingProfile;
const ClassSpendingProfile LOW_INCOME_SPENDING;
const ClassSpendingProfile MIDDLE_INCOME_SPENDING;
const ClassSpendingProfile HIGH_INCOME_SPENDING;

/*Nation performance*/
#define ECONOMIC_GROWTH_MAX 0.04
#define ECONOMIC_GROWTH_FROM_STABILITY 1.0
#define ECONOMIC_GROWTH_FROM_HDI 0.0


#endif